jooj_dougras_v1.0
unleashed-coding/unleashed-coding.github.io pull request #3
Opened 2019-02-01 22:10 UTC by douglasJovenil

jooj do dougras

2019-02-01 22:12 UTC, appositum commented
sai pra la com esses codigo makonha parcero

2019-02-01 22:12 UTC, sqdorte commented
isso aqui é um servidor cristão sem mokoha por favor 🙏🙏

2019-02-01 22:20 UTC, sqdorte requested changes
A gente não precisa desses addons do p5 por enquanto. É melhor só incluir uma referência pra o `p5.min.js` em [uma cdn](https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.min.js).

2019-02-03 18:01 UTC, appositum commented
Movi isso pra outro branch, pra quando tiver tudo certo poder atualizar no gh pages

2019-02-04 03:02 UTC, merged